# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gesundheitsteilchen.de
email: dennis.grothe@uni-bielefeld.de
description: >- # this means to ignore newlines until "baseurl:"
  Geschichten und Projekte rund um das Gesundheitswesen, Public Health und Academia.
twitter_username: freizeitpfleger
github_username: ntgllr
minimal_mistakes_skin:
search: true
locale: "de-DE"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: DE # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - _post_templates
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Dennis Grothe"
  avatar : "/assets/images/Dennis_AG5.jpg"
  bio    : "Ehemaliger Gesundheits- und Krankenpfleger. Studiert Health Communication an der Uni Bielefeld."
  links:
    - label: "Mastodon"
      icon: "fab fa-fw fa-inverse fa-mastodon" 
      url: "https://medibubble.org/@freizeitpfleger"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/dennis-grothe"
    - label: "Mail"
      icon: "far fa-fw fa-envelope"
      url: "mailto:dennis.grothe@uni-bielefeld.de"

footer:
  links:
    - label: "Mastodon"
      icon: "fab fa-fw fa-inverse fa-mastodon" 
      url: "https://medibubble.org/@freizeitpfleger"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/dennis-grothe"
    - label: "Mail"
      icon: "far fa-fw fa-envelope"
      url: "mailto:dennis.grothe@uni-bielefeld.de"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
    #  author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Comments
repository: ntgllr/ntgllr.github.io

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOIjKq2A" # Shown during giscus setup at https://giscus.app
    category_name        : "General" # Full text name of the category
    category_id          : "DIC_kwDOIjKq2M4CS54D" # Shown during giscus setup at https://giscus.app
    discussion_term      : "pathname" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : 1 # '1' for enabled (default), '0' for disabled
    theme                : "light" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"